language: node_js
node_js:
  - 14
script:
  - echo '*** Starting build ***'
  - echo 'Running test'
  - npm test
  - echo 'Start'
  - npm start:dev
deploy:
  provider: heroku
  api_key: SHZCJvOv7NdMZnuw00Ae0Q
  app: travis-ci-codegym
